version: '3.7'
services:
    database:
      image: postgres:latest
      ports:
        - 5432:5432
      restart: always
      environment:
        POSTGRES_USER : docker
        POSTGRES_PASSWORD: docker-postgres
        POSTGRES_DB: data_books
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data

